linkPrefix = "/doxity-demo"
name = "multi_token"
license = "MIT"
version = "1.0.0"
description = ""
author = ""
buildTime = 2018-05-07T13:08:48.269Z
target = "scripts/doxity"
src = "contracts/**"
dir = "pages/docs"
out = "docs"
blacklist = "node_modules/zeppelin-solidity"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"

[interaction]